-- Generated by backend/export_sqlite_to_supabase_sql.py
-- Paste into Supabase SQL editor.
BEGIN;

-- Optional: wipe existing data first (DANGEROUS).
-- TRUNCATE TABLE feedback, epub_notes, epub_bookmarks, notes, bookmarks, listening_progress, epub_progress, users, invite_codes RESTART IDENTITY CASCADE;

-- invite_codes: 4 row(s)
INSERT INTO "invite_codes" ("code", "used_at", "used_by_email")
VALUES
  ('CODE1', '2025-12-13 16:07:16.526896', 'joakim.wassberg@gmail.com'),
  ('CODE2', NULL, NULL),
  ('CODE3', NULL, NULL),
  ('TESTADMIN', '2025-12-16 09:13:12.562424', 'admin1765876392@example.com')
ON CONFLICT DO NOTHING;

-- users: 2 row(s)
INSERT INTO "users" ("id", "name", "email", "password_hash", "is_admin", "created_at", "reader_theme", "reader_font_scale", "reader_line_height")
VALUES
  (1, 'Joakim Wassberg', 'joakim.wassberg@gmail.com', 'scrypt:32768:8:1$1MmG3OSG9UyFazog$1c5181c12e2560d3cc63eb57767e086118cd9d84ed2800e745d45869daf3c700fef34ebc3df08bd85ff9932014e2e3001aa83314e076c52f874c55121b86c04e', TRUE, '2025-12-13 16:07:16.529220', 'paper', 1.1, 1.65),
  (2, 'Admin', 'admin1765876392@example.com', 'scrypt:32768:8:1$CiB9yfGTH1MAGwhE$4c8b772b545017ca7cea602a3824f6a9a357d12d9f1a5a2074fddcc2f8e8d39ab038fcfc0a29e000e1844384162b134798feb3f072d5b879e052092946a6b75b', TRUE, '2025-12-16 09:13:12.564370', 'paper', 1.0, 1.65)
ON CONFLICT DO NOTHING;

-- epub_progress: 1 row(s)
INSERT INTO "epub_progress" ("id", "user_id", "cfi", "chapter_href", "chapter_title", "updated_at")
VALUES
  (1, 1, 'epubcfi(/6/12!/4/2[chapter-two-april-1984-grimethorpe-to-london]/346/1:0)', 'text/ch003.xhtml', 'Chapter Two – April 1984, Grimethorpe to London', '2025-12-13 19:39:56.374795')
ON CONFLICT DO NOTHING;

-- listening_progress: 1 row(s)
INSERT INTO "listening_progress" ("id", "user_id", "chapter_id", "position_seconds", "updated_at")
VALUES
  (1, 1, 'chapter00', 64.502583, '2025-12-18 08:11:19.071540')
ON CONFLICT DO NOTHING;

-- bookmarks: 0 row(s)

-- notes: 0 row(s)

-- epub_bookmarks: 0 row(s)

-- epub_notes: 2 row(s)
INSERT INTO "epub_notes" ("id", "user_id", "cfi", "chapter_href", "chapter_title", "text", "created_at", "updated_at", "note_type", "severity", "spoiler", "excerpt")
VALUES
  (1, 1, 'epubcfi(/6/14!/4/2[chapter-three-junejuly-1984-london-bedsit-and-orgreave-enemy-within]/2/1:0)', 'text/ch004.xhtml', 'Chapter Three – June–July 1984, London Bedsit and Orgreave / “Enemy Within”', 'Chapter 3 is good', '2025-12-13 19:39:38.936744', '2025-12-13 19:39:38.936749', NULL, NULL, FALSE, NULL),
  (2, 1, 'epubcfi(/6/12!/4/2[chapter-two-april-1984-grimethorpe-to-london]/346/1:0)', 'text/ch003.xhtml', 'Chapter Two – April 1984, Grimethorpe to London', 'The end of chapter 2 is odd', '2025-12-13 19:40:05.678551', '2025-12-13 19:40:05.678557', NULL, NULL, FALSE, NULL)
ON CONFLICT DO NOTHING;

-- feedback: 1 row(s)
INSERT INTO "feedback" ("id", "user_id", "scope", "chapter_id", "text", "created_at", "status", "draft_version")
VALUES
  (1, 1, 'chapter', 'chapter00', 'Ratings: clarity 4/5, pacing 3/5, characters 4/5

Good start', '2025-12-16 09:11:04.949634', 'triaged', NULL)
ON CONFLICT DO NOTHING;

-- Reset sequences (if you inserted explicit ids).
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM "users"), 1));
SELECT setval(pg_get_serial_sequence('epub_progress', 'id'), COALESCE((SELECT MAX(id) FROM "epub_progress"), 1));
SELECT setval(pg_get_serial_sequence('listening_progress', 'id'), COALESCE((SELECT MAX(id) FROM "listening_progress"), 1));
SELECT setval(pg_get_serial_sequence('bookmarks', 'id'), COALESCE((SELECT MAX(id) FROM "bookmarks"), 1));
SELECT setval(pg_get_serial_sequence('notes', 'id'), COALESCE((SELECT MAX(id) FROM "notes"), 1));
SELECT setval(pg_get_serial_sequence('epub_bookmarks', 'id'), COALESCE((SELECT MAX(id) FROM "epub_bookmarks"), 1));
SELECT setval(pg_get_serial_sequence('epub_notes', 'id'), COALESCE((SELECT MAX(id) FROM "epub_notes"), 1));
SELECT setval(pg_get_serial_sequence('feedback', 'id'), COALESCE((SELECT MAX(id) FROM "feedback"), 1));

COMMIT;
